version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    restart: on-failure
    volumes:
      - .:/go/src/ticket
    ports:
      - "80:8080"
    networks:
      - ticketNetwork
  
networks:
  ticketNetwork:
    driver: bridge






