version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    restart: on-failure
    volumes:
      - .:/go/src/ticket
    ports:
      - "80:8080"
    networks:
      - ticketNetwork

  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - ticketNetwork
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    networks:
      - ticketNetwork
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=
      - ME_CONFIG_MONGODB_ADMINPASSWORD=
      - ME_CONFIG_MONGODB_SERVER=mongodb
  
networks:
  ticketNetwork:
    driver: bridge






